### ISSUE TITLE
Bookmark explenation

### ISSUE THREAD

**Issue by alolalo** [oxalorg/sakura#112]
Hi Sakura Makers,

I was really wondering how you got the "Bookmark" function to work with any website. It's much like how you would use @import or link rel:() without having to worry about any removal.

For me I would like to use it for the baseline of my design system RevolverDS, so that I can lock, load & ship the basics in just like you did so gracefully. 

Pointing to the code that does so would be great, I have lots to learn on the back of the front

**Comment by oxalorg** [comment]
Here's the code: https://github.com/oxalorg/sakura/blob/master/src/bookmarklet.js :) 🌸
