### ISSUE TITLE
Refreshing the documentation's deployment

### ISSUE THREAD

**Issue by zhakk-harn** [oxalorg/sakura#126]
Hi,

The [webpage for the documentation ](https://oxal.org/projects/sakura/) is quite out of sync with the readme.

Which could be fine. Except when you look at the "Sites using Sakura" section. 

Right now only two sites are listed, one isn't using sakura, the other got pwned and is now redirecting its traffic to a porn site.

**Comment by oxalorg** [comment]
Thanks a lot, appreciate the headsup! I've updates it https://oxal.org/projects/sakura/ 🌸
