### ISSUE TITLE
Font-family in theming

### ISSUE THREAD

**Issue by indigotock** [oxalorg/sakura#17]
I think it could be very useful for separating concerns if the serif and sans-serif font families were included in the Sakura theme.scss as a variable or mixin. I don't think it would be breaking the spirit of keeping Sakura 'as simple as possible'. As of right now the font-families are only declared once each in the base SASS file, but I think they are more related to the specific theme :thought_balloon:. 

The two clear options I see are (as above) variables:
```sass
$font-sans-serif: Verdana, Geneva, sans-serif;
$font-serif: serif;
...
font-family: $font-sans-serif();
```
and mixins:
```sass
@mixin font-sans-serif() {
    font-family: Verdana, Geneva, sans-serif;
}

@mixin font-serif() {
    font-family: serif;
}
...
@include font-sans-serif();
```
Saklura can then just use these as defined in the theme as it already does for colours and `font-size-base`.

The reason for the mixin suggestion is that the different font faces would have an impact on the size of the glyphs (e.g. [Libre Baskerville vs. times](https://codepen.io/indigotock/pen/rwRwGM)), so fonts might need to be scaled slightly because of this (but I would say this strays slightly away form keeping Sakura simple).

This is going to be pretty easy to implement, but some discussion is needed as to whether it should even be done and if so, the method to use. 

Any thoughts?

**Comment by oxalorg** [comment]
Thanks for the PR, merged it. I was planning on doing this but couldn't find the time. 🐱 

I'd want to put a hold onto the mixins with different font sizes for now because like you said it would break the idea of keeping things as simple as possible. ^_^

Though if theres a real need (?), this could be left open for discussion.
