### ISSUE TITLE
Radio button broken on Chrome 

### ISSUE THREAD

**Issue by russlamb** [oxalorg/sakura#19]
v 60.0.3112.101

Radio buttons show up as ovals and "selected" indicator (the dot) shows up outside of the shape.

EDIT:
when i remove the padding, as per the comment below, it reverts to a circle and works again.  

```

textarea, select, input[type] {
 
  /* The 6px vertically centers text on FF, ignored by Webkit */
   
  /* this padding makes radio buttons oblong and the dot inside falls outside of its shape*/
  /*padding: 6px 10px;*/
  color: #4a4a4a;
  margin-bottom: 10px;
  background-color: #f1f1f1;
  border: 1px solid #f1f1f1;
  border-radius: 4px;
  box-shadow: none;
  box-sizing: border-box; }
  textarea:focus, select:focus, input[type]:focus {
    border: 1px solid #2c8898;
    outline: 0; }
```

**Comment by oxalorg** [comment]
Hey sorry for the delayed response. 

I am unable to reproduce this on `Chrome Version 80.0.3987.149 (Official Build) (64-bit)` with or without `normalize.css`

Please re-open if this is still an issue, and I will check into it asap. :)
