### ISSUE TITLE
Demo site down?

### ISSUE THREAD

**Issue by jsprow** [oxalorg/sakura#22]
Howdy,
I was just heading over to your demo so that I could evaluate your project (Looks good so far, BTW!), but it's down! Not sure if you're doing maintenance or what, but I thought you'd like to know.

Here's what I get when I go to https://oxal.org:
![screen shot 2018-03-06 at 5 14 25 pm](https://user-images.githubusercontent.com/15620432/37061658-1d6022fc-2162-11e8-8f17-9bcab1170c93.jpg)

... and when I click the link to https://oxal.org/projects/sakura/demo, it redirects to:
![screen shot 2018-03-06 at 5 15 05 pm](https://user-images.githubusercontent.com/15620432/37061699-46cf7930-2162-11e8-82b5-b63e91517dbe.jpg)

Let me know if you'd like any more info!

**Comment by oxalorg** [comment]
Extremely sorry. My droplet died after an emergency maintenance by DigitalOcean. I've migrated the site to another droplet and the demo is back up! ^_^

**Comment by jsprow** [comment]
No need to apologize! Thanks for all your hard work.
