### ISSUE TITLE
(docs) installation section missing package manager subsection

### ISSUE THREAD

**Issue by zenflow** [oxalorg/sakura#24]
Under [Installing](https://github.com/oxalorg/sakura#installation) it should have instructions to install from npm or yarn. Without this it looks like it can't be installed from the npm registry as a dependency in one's project. 

Happy to PR

**Comment by oxalorg** [comment]
Hi @zenflow 

You can install sakura using `yarn add sakura.css` or `npm install sakura.css` to be used as a dependency.

Though this isn't mentioned in the README.md, and I'd be happy to take a PR for it! :)
