### ISSUE TITLE
Demo of all built-in themes on README

### ISSUE THREAD

**Issue by ssebs** [oxalorg/sakura#4]
Hi,
I think you should add all of the themes on your demo site, or add a GH pages site for sakura with a demo of all the built-in themes.

Thanks

**Comment by oxalorg** [comment]
Awesome suggestion. I implemented it and updated the demo page https://oxal.org/projects/sakura/demo/ in this commit:
 (https://github.com/oxalorg/oxal.org/commit/e41e9f8fe66b63603d16f0859cdd07348da295b6)
