### ISSUE TITLE
No CSS for a:visited

### ISSUE THREAD

**Issue by lucas-deangelis** [oxalorg/sakura#40]
Thank you for sakura!

It seems that there's no specific CSS for visited links (`a:visited`). I think it would be a great addition, considering this is a basic feature of browser, and removing it I think makes the browsing experience a bit worse.

**Comment by oxalorg** [comment]
Hey @lucas-deangelis , nice catch!

You're right it'll make the browing experience more consistent. We'll have to think of a color substituation which will work with all our themes. 

Something like `darken($color-fade, 20%)` perhaps.

**Comment by lucas-deangelis** [comment]
I think something like what you proposed would be great. Since there's another issue with link colors (#7), maybe we should try to tackle them both at once? We could find colors that are accessible even when darkened for each theme (if they are not right now).

**Comment by oxalorg** [comment]
@lucas-deangelis Would you like to give this a go? The #7 contrast issue has already been fixed!

**Comment by lucas-deangelis** [comment]
Thanks for giving me this opportunity. I've made a pull request with my proposed changes and screenshots.

**Comment by oxalorg** [comment]
@lucas-deangelis Thank you once again for this PR. Really appreciate your attention to detail.

Cheers

**Comment by lucas-deangelis** [comment]
Thank you for being so welcoming and positive!
