### ISSUE TITLE
Focus state for checkboxes in Firefox

### ISSUE THREAD

**Issue by JaroVDH** [oxalorg/sakura#5]
Firefox doesn't like some styles on checkboxes for some antiquated reasons, which results in no focus state.
You remove the default one, and the custom border isn't getting added.

**Comment by oxalorg** [comment]
Sorry but I do not understand how to reproduce this (firefox isn't doing anything on checkbox focus on any website for me). Could you point me in the right direction?

**Comment by JaroVDH** [comment]
![focus](https://cloud.githubusercontent.com/assets/6927640/25776201/89951b92-32b8-11e7-9157-a3a865df1c72.png)
Here's what it looks like default, as shown on your test page.
Might not be very visible to us, but it's very useful for people who rely on keyboard navigation.
