### ISSUE TITLE
<pre><code> font smaller than <pre> font in a minimal html

### ISSUE THREAD

**Issue by pietroppeter** [oxalorg/sakura#50]
Opening the following minimal html in a browser:

```html
<!DOCTYPE html>
<html>
<head>
  <meta content="text/html; charset=utf-8" http-equiv="content-type">
  <meta content="width=device-width, initial-scale=1" name="viewport">
  <link rel='stylesheet' href='https://unpkg.com/normalize.css/' type='text/css'>
  <link rel="stylesheet" href="https://unpkg.com/sakura.css/css/sakura.css" type="text/css">
</head>
<body>
  <pre><code>I am smaller </pre></code>
  <pre>I am bigger</pre>
</body>
</html>
```

I see this:

![image](https://user-images.githubusercontent.com/4997234/94287576-c5431680-ff56-11ea-83da-e75540fc9da4.png)

I have no idea why this happens. Opening in the same browser (Chrome Dev 85.0.4183.102 on Windows 10) sakura standard demo (https://oxal.org/projects/sakura/demo/) I see the correct size for code element. I have tried inspecting the elements to see differences and also tested with a fresh local sakura.css but I was not able to find the issue. I also opened a locally downloaded copy of above demo and I still see it correctly.

**Can somebody reproduce this?** Some explanation for this effect?

### Edit

I found an explanation for why this does not happen with sakura demo. testing a stripped down version of the demo containing only two elements like in the above file I realized that the demo never uses a `<pre>` element alone, but always with a `<code>` element inside. The strange font-size behaviour happens for `<pre><code>` element when a `<pre>` element without `<code>` is on the page.

Is it supposed to be like this?

Incidentally, a HTML5 test page like the one used in latex.css (https://latex.now.sh/elements#text__code) could be useful to be available also on top of the demo and I suspect it might show the same issue.

### Further Edit

I was initially confused and at some point thought the mere presence of an isolated `pre` tag somewhere caused the reduction of size for the font of all `<pre><code>` tags in the page. Of course, that would have been crazy and nothing of the sorts happen 😅

**Comment by oxalorg** [comment]
Yes, you are right. I had initially set `font-size` for `code` tags to be 10% smaller because I usually use a monospace font for code.

Monospace fonts are usually larger in size than serif/sans-serif. To compensate for that I must have originally reduced the size of the code tag.

We can either reduce the size of `pre` tag too or just get rid of this assumption. Any thoughts are welcome!

**Comment by pietroppeter** [comment]
Thanks for the quick reply!

Another html:

```html
<!DOCTYPE html>
<html>
<head>
  <meta content="text/html; charset=utf-8" http-equiv="content-type">
  <meta content="width=device-width, initial-scale=1" name="viewport">
  <link rel='stylesheet' href='https://unpkg.com/normalize.css/' type='text/css'>
  <link rel="stylesheet" href="https://unpkg.com/sakura.css/css/sakura.css" type="text/css">
</head>
<body>
  <p>Paragraph with <code>code</code> inline (default size)</p>
  <p>Paragraph with <code style="font-size: 1em;">code</code> inline (size <tt>1em</tt>)</p>
  <pre><code>This is code inside pre</pre></code>
  <pre>This is just pre</pre>
</body>
</html>
```

looks like this:

![image](https://user-images.githubusercontent.com/4997234/94306868-04339500-ff74-11ea-8b09-86df5a64ae57.png)

Looking at the above, my personal thought is that `code` is a bit small with respect to normal text (more evident from inline code element). Actually it seems that monospace font is smaller than normal even when at same nominal size. I would probably get rid of the assumption.

**Comment by oxalorg** [comment]
I checked it on a couple of fonts, and typically monospace fonts tend to consume larger visual space for the same content as other fonts.

On my blog: https://oxal.org/blog/fizzbuzz-in-clojure/ setting `code` to the same size as the text looks weird and non-proportional. 

Bootstrap also seems to be reducing the font size of `pre` and `code` tags.

So I feel like we should keep the small size of `code` and make it consistent by adding it to `pre` as well.

**Comment by pietroppeter** [comment]
You definitely have much more experience than me to judge on this (mine is not much more than the two examples above 😄) so go ahead with what you feel better for the project! And thanks for sakura which is very nice!

**Comment by roj1512** [comment]
What about this workaround?

```stylus
pre
  code
    font-size inherit
 ```

**Comment by oxalorg** [comment]
That's a great idea! Nice thinking :)

There was a different approach to solve this in #52 it seems. I've merged that in. But pre > code inherit seems more cleaner. Either works :) 

Feel free to add a PR if you want to update it!
