### ISSUE TITLE
Add `prefers-color-scheme` to recognize dark mode

### ISSUE THREAD

**Issue by csterritt** [oxalorg/sakura#58]
Don't like it myself :-) but some folks really like dark mode, and evidently adding the following media query works:

``` css
@media (prefers-color-scheme: dark) {
    // ... dark styles ...
}
```

Thanks for doing Sakura!  I like it a lot.

**Comment by lesderid** [comment]
I'd like to use Sakura as the default stylesheet for a static page generation tool I'm working on, and it would be great if this was supported.

I think ideally there would be three CSS files after this change (in addition to other tertiary schemes): light, dark, and both.

The first two files would have `:root { color-scheme: light; }` and `:root { color-scheme: dark; }` respectively, while the last one would use `prefers-color-scheme`. This leaves the option to have a small file if you only want to support one colour scheme.

**Comment by roj1512** [comment]
You something like this:

```css
@import "https://unpkg.com/sakura.css/css/sakura.css";
@import "https://unpkg.com/sakura.css/css/sakura-dark.css" (prefers-color-scheme: dark);
```

**Comment by oxalorg** [comment]
That is a great idea @roj1512.

I would go one step further and do this directly in the HTML `link` tag using a `media` attribute. Link is preferable over imports for both performance reasons and flexibility to change (include exclude).

```html
 <link rel="stylesheet" href="https://unpkg.com/sakura.css/css/sakura.css" media="screen" />
<link rel="stylesheet" href="https://unpkg.com/sakura.css/css/sakura-dark.css" media="screen and (prefers-color-scheme: dark)" />
```

**Comment by csterritt** [comment]
@oxalorg Thanks! That works perfectly on my site. Much appreciated!
