### ISSUE TITLE
[Feature Request] Admonitions

### ISSUE THREAD

**Issue by RoyiAvital** [oxalorg/sakura#59]
This is a great and clean `CSS`.

Any chance of having Admonitions.  
Something like in Jupyter will be great: https://jupyterbook.org/content/content-blocks.html.

**Comment by oxalorg** [comment]
@RoyiAvital That's a good idea, what is your suggestion to add these? 

Since we're _mostly_ classless, is there an existing html element where we can do something? If not which classes should we use and how detailed should we go in the design!

Any thoughts would be appreciated! 😄

**Comment by RoyiAvital** [comment]
This is great. Is there a demo of what was implemented?
