### ISSUE TITLE
Add Name IN Sakura List

### ISSUE THREAD

**Issue by SleepBag123** [oxalorg/sakura#65]
Hi @oxalorg  I saw that the readme states that if I do use sakura, you would love to include my sites name in the list so here is another addtion for your list 

[http://kjani.xyz](url)

**Comment by oxalorg** [comment]
Hehe sakura isn't ugly, it's just simple!! 🙈 😁 

Would you want to send a PR for this addition? :)

**Comment by SleepBag123** [comment]
For me its beauty but for most people who usually visit bloated sites with a hell lot of java script it may not look at par that is why I added that post, but for me I LOVE IT
