### ISSUE TITLE
Confusing style of buttons after being clicked

### ISSUE THREAD

**Issue by spenserblack** [oxalorg/sakura#98]
It appears that `button:hover` and `button:focus` have the exact same styling. IMO this is confusing because a button can remain focused after being clicked, so it visually looks like it's still being hovered over. This can be seen in the current `test.html`. If you click on the "Switch" button, then the styling of the clicked button will be different than the button above it.

**Comment by oxalorg** [comment]
Thanks for the bug fix! PR coming up :) LMK if this works

**Comment by spenserblack** [comment]
Yeah, looks like that works, thanks!
